### ISSUE TITLE
Error using patch Value must be of numeric type and greater than 1.  Error in trimesh (line 118) h = patch('faces',trids,'vertices',[x(:) y(:) z(:)],'facevertexcdata',c(:),...  Error in my_mesh_1 (line 144) trimesh(tri,x,y,z);

### ISSUE THREAD

**Issue by Aayush146** [LHEEA/Nemoh#11]
Hi I am getting a new error. It seems that certain values are coming to be smaller than 1 in the x y z variables. Could anyine please guide me through this

**Comment by gducrozet** [comment]
This project has migrated to GitLab: https://gitlab.com/lheea/Nemoh

If the issue is still active in the new Release, feel free to open an issue there!
