### ISSUE TITLE
Invalid file identifier. Use fopen to generate a valid file identifier. Separate Mesh File

### ISSUE THREAD

**Issue by ikaushik007** [LHEEA/Nemoh#12]
Hello there, so I am trying to use Nemoh to find my coefficients for a sphere for use in WEC-sim. I used BEMROSETTA to convert my STL files into NEMOH.dat file for input into NEMOH and then planned to use the coefficients obtained from NEMOH in WEC-Sim for analysis of my device.

However, when I run Nemoh through MATLAB, I get the same error. full error below

Error using fgets
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in fgetl (line 32)
[tline,lt] = fgets(fid);

Error in Nemoh (line 104)
ligne=fgetl(fid);

Error in nemoh_run (line 9)
[A,B,Fe]=Nemoh(w,dir,depth);

Is there any guide on using an already mesh and running nemoh.

**Comment by gducrozet** [comment]
Hello @ikaushik007 
It looks like an error external to NEMOH, check the path and name of the file you provide as input. Matlab simply tells you that he cannot read the file. You should have prior to the 'fgets' command a 'fid=fopen(...)' to tell the code which file you open!?

Best,
G.

**Comment by ikaushik007** [comment]
fid=fopen([rep,filesep,'results',filesep,'ExcitationForce.tec'],'r'); 

this is the line that throws an error. I have checked and ensured that the directory is made but I still get this error.

**Comment by gducrozet** [comment]
Since it is not an issue with the core of NEMOH, it is a bit out of our hands... Check filesep is coherent with your Operating System and that [rep,filesep,'results',filesep,'ExcitationForce.tec'] points really toward your file.
Otherwise, check the readability of your file.

**Comment by hfpim** [comment]
@gducrozet I am having the same issue and I believe there is something odd with Nemoh's Solver.exe.
I'm working on a similar project as @ikaushik007 and upon further debugging I found that the solver only runs the first problem out of 133 (in my case) and then jumps to post-processing, where the error mentioned above appears. 
I checked the file paths and they all look ok. I don't know how to proceed from there

**Comment by gducrozet** [comment]
I am a bit doubtful this issue is related to NEMOH if it points toward an error in the fopen...

By the way, for your information, we are preparing a new major Release that should solve some issues and possibly the present execution one (if it is really related to NEMOH and not Matlab).
In addition, GitHub will be replaced soon by Gitlab for the 'official' repository of Nemoh (with several new features to come!!).

**Comment by hfpim** [comment]
Thank you for the update. How would you recommend I proceed? Any reasons why the solver only solves the first calculation and then moves on to post-processing? Any chance I might be setting up the Nemoh.cal file wrong or something else?
I hit a dead end and I don't know how to move forward.

**Comment by gducrozet** [comment]
This project has migrated to GitLab: https://gitlab.com/lheea/Nemoh

If the issue is still active in the new Release, feel free to open an issue there!
