### ISSUE TITLE
Diffraction and excitation IRFs, Diffraction and excitation forces in time domain

### ISSUE THREAD

**Issue by zanderder** [LHEEA/Nemoh#13]
Dear all,

Does anyone know how to acquire diffraction and excitation IRFs from Nemoh and how to convert diffraction and excitation forces to time domain? Nemoh provides DiffractionForce, ExcitationForce, and FKForce in frequency domain. I am wondering how to convert them to time domain. From the literature, the excitation force in time domain can be obtained using (for regular wave):

F_ex(t) = R{ H/2 * F_ex(w) * exp(i*w*t) }, 

where H is the wave height, w is the wave frequency, R is to extract the real part, i is the imaginary unit, F_ex(w) and F_ex(t) are excitation forces in frequency and time domains, respectively. 

However, I do not know how to convert the diffraction force to time domain. I am aware of that excitation force is the sum of diffraction force and FK force. So, does that mean I can obtain their time domain counterparts through the following linear decomposition?

F_ex(w) = F_d(w) + F_fk(w),
F_d(t) =  R{ H/2 * F_d(w) * exp(i*w*t) }, 
F_fk(t) =  R{ H/2 * F_fk(w) * exp(i*w*t) }, 

I am not sure. All these forces have their phase angles according to the result files generated by Nemoh, how to involve them in the conversion?

Besides, I am also thinking of acquiring the IRFs of diffraction and excitation forces. Nemoh only gives the IRF of radiation force directly. How to obtain the other two? I intend to use them in a time-domain analysis. Knowing the IRF, the diffraction and excitation forces in time domain can also be obtained using:

F(t) = - integral { K(t-tau) * eta(t) } dt

where K(t) is the IRFs, eta(t) is the free-surface elevation. 

Any suggestion? 

Thanks. 

Regards,
Zander

**Comment by mancellin** [comment]
Sounds good overall, but note that Nemoh uses the convention `exp(-iωt)` (unlike e.g. WAMIT which uses the convention `exp(iωt)`), so you're missing a minus in your exponentials.

> All these forces have their phase angles according to the result files generated by Nemoh, how to involve them in the conversion?

$R(F \exp(-iωt)) = R(|F| \exp(-iωt + i\mathrm{phase}(F)) = |F| \cos(-ωt + \mathrm{phase}(F))$
Something like that?

Edit: fix $i$'s in the above equation.

**Comment by zanderder** [comment]
Thank you Mancellin for your comments and reminder. 

> Sounds good overall, but note that Nemoh uses the convention `exp(-iωt)` (unlike e.g. WAMIT which uses the convention `exp(iωt)`), so you're missing a minus in your exponentials.

I was not aware of the convetion exp(-iwt). Big thanks.
 
> R(Fexp⁡(−iωt))=R(|F|exp⁡(−iωt+phase(F))=|F|cos⁡(−iωt+phase(F)) Something like that?

I just learnt from [the Notations and conventions, Nemoh-Theory](https://lheea.ec-nantes.fr/valorisation/logiciels-et-brevets/nemoh-theory) that the excitation force in time domain is:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/54009076/193969779-14fdad01-15db-42d0-9ab1-9ff8b5b3b492.png">

But I am still not sure whether both diffraction and FK forces in time domain can be calculated using the same equation as above.

Thanks.

Regards,
Zander

**Comment by zanderder** [comment]
I just carried out a numerical calculation and verified that both diffraction and FK forces in time domain can be calculated using the above equation. Guess because all these three forces are linear. 

Regards,
Zander

**Comment by gducrozet** [comment]
Issue solved.
