### ISSUE TITLE
Free surface elevation

### ISSUE THREAD

**Issue by Dylan0824** [LHEEA/Nemoh#15]
Dear all
  
  Hi, I want to use Nemoh to calculate the freesurrface elevation. And i get 7 files about free surface of each problem under one 

![1669030991769](https://user-images.githubusercontent.com/115965311/203043232-bc93acd1-1ca2-4faf-b2ad-410335530ed5.png)
![1669031002462](https://user-images.githubusercontent.com/115965311/203043241-427ba075-01f2-4fb2-8a14-401812632fa6.png)
frequency.

  And, I want to know how to calculate the real free surface elevation. By summing them all?

  Can anyone tell me. And thank you all guys!

G

**Comment by gducrozet** [comment]
This project has migrated to GitLab: https://gitlab.com/lheea/Nemoh

If the issue is still active in the new Release, feel free to open an issue there!
