### ISSUE TITLE
hydroelasticity example

### ISSUE THREAD

**Issue by phthree** [LHEEA/Nemoh#2]
Hi all,
I would like to investigate a flexible plate floating on water surface. I saw the introduction that the Nemoh has the ability to deal with hydroelasticity problem. But I can not find any further information. Can you share an example about it?
Many thanks in advance.

**Comment by Tudore** [comment]
how is your progress？

**Comment by gducrozet** [comment]
This project has migrated to GitLab: https://gitlab.com/lheea/Nemoh

If the issue is still active in the new Release, feel free to open an issue there!
