### ISSUE TITLE
Triangular mesh

### ISSUE THREAD

**Issue by robeche** [LHEEA/Nemoh#5]
Dear developers,

is it possible to use triangles combined with quadrilaterals in a mesh?

kind regards

Roberto

**Comment by mancellin** [comment]
Dear Roberto,

For Nemoh, a triangle is a quadrilateral with two identical vertices. So mixing triangles and quadrilaterals should not be a problem: everything will be seen as quadrilaterals anyway.

**Comment by gducrozet** [comment]
This solves the issue that I close then!
