### ISSUE TITLE
Fortran runtime error

### ISSUE THREAD

**Issue by rohitalexander** [LHEEA/Nemoh#8]
Hello! I've been working on a project which requires the use of NEMOH. Since I am completely new to it, I thought of running the vertical cylinder example given in the NEMOH folder. On trying to run the Matlab code Nemoh.m, I receive the following error:
------ Starting NEMOH ----------- 
At line 138 of file preProcessor/Main.f90 (unit = 10, file = './Nemoh.cal')
Fortran runtime error: Bad integer for item 1 in list input

Error termination. Backtrace:
#0  0x10208b757
#1  0x10208c3db
#2  0x10208cd73
#3  0x10214d907
#4  0x10215016b
#5  0x102150c2f
#6  0x10206fb4b
#7  0x10207252f
------ Solving BVPs ------------- 
  
  -> Initialisation At line 73 of file Solver/Core/Bodyconditions.f90 (unit = 10, file = './Normalvelocities.dat')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x1050cb757
#1  0x1050cc3db
#2  0x1050ccd73
#3  0x105195f83
#4  0x1051900d7
#5  0x105190c2f
#6  0x104e3693f
#7  0x104e4a947
#8  0x104e4c22f
------ Postprocessing results --- 
  
  -> Initialisation .At line 113 of file Common/Results.f90 (unit = 10, file = './results/index.dat')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x102f5b757
#1  0x102f5c3db
#2  0x102f5cd73
#3  0x103025f83
#4  0x1030200d7
#5  0x103020c2f
#6  0x102f45433
#7  0x102f497f3
#8  0x102f49b9f

I don't know if it is relevant, but I am running the code on macOS Big Sur and have used the makefile as per the instructions. Looking forward to hearing your thoughts and advices!

Cheers,
Rohit

**Comment by gducrozet** [comment]
For your information, we are preparing a new major Release that should fix compilation issues.
In addition, GitHub will be replaced soon by Gitlab for the 'official' repository of Nemoh (new features to come!!).

Then, I close the issue which will hopefully not appear again in the new version.
